#!/usr/bin/env bash
# Transfering file to the remote server
# using secure copy(scp) command
# $1: path of file to be transfered
# $2: Ip address/domain-name of the server
# $3: username server is connected with
# $4: path to ssh private key to be used
# $5: path of where we'll save our file
# scp Generally works in the following ways
# scp $1 $3@$2:$5
# USERNAME=$3
# Ip=$2
# PATH_TO_FILE=$1

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi