#!/usr/bin/env bash
# This script installs Nginx, creates a custom index.html page, and restarts Nginx

# Update package list
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Remove the default index.html file
rm -f /var/www/html/index.html

# Create a new index.html file with the required content
echo "<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Holberton School for the win!</h1>
</body>
</html>" | tee /var/www/html/index.html

# Restart Nginx
service nginx restart





