#!/usr/bin/env bash
# Script that configures a new Ubuntu machine with Nginx to meet the specified requirements

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Set the homepage content
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Backup the original configuration file
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak

# Configure redirection
sudo sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.github.com/NsengaNigel;\n    }' /etc/nginx/sites-enabled/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the changes
sudo service nginx reload
