#!/usr/bin/env bash
# This script installs Nginx, configures a custom 404 page, and restarts the server.

# Install Nginx
apt-get update -y
apt-get install nginx -y

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Update Nginx configuration to use the custom 404 page
sed -i '/^\tlocation \/ {/ a\\n\t\t# Custom 404 error page\n\t\terror_page 404 /404.html;\n\t\tlocation = /404.html {\n\t\t\tinternal;\n\t\t}' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

exit 0

